apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: app
  namespace: monitoring  
spec:
  selector:
    matchLabels:
      app: app
  namespaceSelector:
    matchNames:
      - default  
  endpoints:
    - port: metrics  
      path: /metrics
      interval: 15s
      honorLabels: true
