apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: vm
    meta.helm.sh/release-namespace: monitoring
  name: vm-grafana-n
  namespace: monitoring
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30000
  selector:
    app.kubernetes.io/instance: vm
    app.kubernetes.io/name: grafana
  type: NodePort

