apiVersion: v1
kind: Service
metadata:
  name: prometheus-app-grafana-node
  namespace: monitoring
spec:
  ports:
  - name: http-web
    port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30000
  selector:
    app.kubernetes.io/instance: prometheus-app
    app.kubernetes.io/name: grafana
  type:  NodePort
