apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/akbarmohammadi70/test_k8s.git"
    targetRevision: master
    path: "03-PrometheusStack/servicemonitor"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - CreateNamespace=false
