all:
  hosts:
    master:
      ansible_host: 5.34.207.188
  vars:
    ansible_user: ubuntu
    longhorn_data_path: "/data"
    ingress_domain: "longhorn.damy.ir"
    ingress_basic_auth_user: "admin"
    ingress_basic_auth_password: "admin1234"