---
- name: Install Longhorn with Helm and Ingress
  hosts: all
  become: true
  gather_facts: false
  vars:
    longhorn_data_path: /data
    ingress_domain: longhorn.damy.ir
  tasks:
    - name: Add Longhorn Helm repository
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: https://charts.longhorn.io
        state: present

    - name: Install Longhorn with Helm
      kubernetes.core.helm:
        name: longhorn
        chart_ref: "longhorn/longhorn"
        release_namespace: longhorn-system
        create_namespace: true
        values:
          persistence:
            defaultClass: true
          storageClass:
            defaultClass: true
            defaultClassReplicaCount: 2
            defaultClassStaleReplicaTimeout: 30
            defaultClassDataPath: "{{ longhorn_data_path }}"
          defaultSettings:
            defaultDataPath: "{{ longhorn_data_path }}"
            storageMinimalAvailablePercentage: 10
            storageOverProvisioningPercentage: 200
            replicaSoftAntiAffinity: true
            allowVolumeCreationWithDegradedAvailability: true
          longhornDefaultSettings:
            recurringJobs: true

    - name: Verify Longhorn installation
      shell: "kubectl -n longhorn-system get pod"
      register: longhorn_pod_status

    - debug:
        var: longhorn_pod_status.stdout_lines

    - name: Create Basic Authentication Secret
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          data:
            auth: YWRtaW46JGFwcjEkM0ZQMGlBNkMkcHNrdWptay9HdmoycmQ5TnVRdTlrLgo=
          kind: Secret
          metadata:
            name: basic-auth
            namespace: longhorn-system

    - name: Configure Ingress for Longhorn UI with Basic Authentication
      kubernetes.core.k8s:
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: longhorn-ui-ingress
            namespace: longhorn-system
            annotations:
              # type of authentication
              nginx.ingress.kubernetes.io/auth-type: basic
    # prevent the controller from redirecting (308) to HTTPS
              nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    # name of the secret that contains the user/password definitions
              nginx.ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropriate context why the authentication is required
              nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required '
    # custom max body size for file uploading like backing image uploading
              nginx.ingress.kubernetes.io/proxy-body-size: 10000m
          spec:
            ingressClassName: nginx
            rules:
              - host: "{{ ingress_domain }}"
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: longhorn-frontend
                          port:
                            number: 80

    - name: Output Ingress access instructions
      debug:
        msg: "Access Longhorn UI at http://{{ ingress_domain }} with Basic Authentication credentials"

    - name: Output Basic Authentication credentials
      debug:
        msg: "Basic Authentication credentials: {{ ingress_basic_auth_user }} / {{ ingress_basic_auth_password }}"