name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file ./06-App/Dockerfile --tag akbar1370/test_k8s:$(date +%H) && echo "dckr_pat_IPXJo9r86AkTQS4gc62GMtcEElo" | docker login -u akbar1370 --password-stdin && docker push akbar1370/test_k8s:$(date +%H)
      
