name: Docker Image CI

on:
  push:
    branches: 
      - "master"
  pull_request:
    branches: 
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4    
    - name: Build Docker image
      run: |
        docker build . --file ./05-App/Dockerfile --tag akbar1370/test_k8s:latest
        echo "Image built successfully."

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: akbar1370
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push akbar1370/test_k8s:latest
        echo "Docker image pushed successfully."
